name: Docker Build and Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t vulnerable-app .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: vulnerable-app
          format: table
          exit-code: 0
